# src/feature_labels.py

FEATURE_LABELS = {
    # =========================
    #   FEATURES DE BASE
    # =========================
    "SK_ID_CURR": "Identifiant client",
    "NAME_CONTRACT_TYPE": "Type de contrat",
    "CODE_GENDER": "Sexe",
    "FLAG_OWN_CAR": "Possède une voiture (0/1)",
    "FLAG_OWN_REALTY": "Possède un bien immobilier (0/1)",
    "CNT_CHILDREN": "Nombre d'enfants",
    "AMT_INCOME_TOTAL": "Revenu annuel",
    "AMT_CREDIT": "Montant du crédit demandé",
    "AMT_ANNUITY": "Montant de l'annuité",
    "AMT_GOODS_PRICE": "Prix du bien financé",
    "NAME_TYPE_SUITE": "Type d'accompagnement (seul, famille, etc.)",
    "NAME_INCOME_TYPE": "Type de revenu",
    "NAME_EDUCATION_TYPE": "Niveau d'étude",
    "NAME_FAMILY_STATUS": "Situation familiale",
    "NAME_HOUSING_TYPE": "Type de logement",
    "REGION_POPULATION_RELATIVE": "Population relative de la région",
    "DAYS_BIRTH": "Âge (jours, négatif)",
    "DAYS_EMPLOYED": "Ancienneté dans l'emploi (jours, négatif)",
    "DAYS_REGISTRATION": "Ancienneté de l'inscription (jours, négatif)",
    "DAYS_ID_PUBLISH": "Ancienneté de mise à jour des papiers (jours, négatif)",
    "OWN_CAR_AGE": "Âge du véhicule (années)",
    "FLAG_MOBIL": "Téléphone mobile renseigné (0/1)",
    "FLAG_EMP_PHONE": "Téléphone professionnel renseigné (0/1)",
    "FLAG_WORK_PHONE": "Téléphone de travail renseigné (0/1)",
    "FLAG_CONT_MOBILE": "Mobile joignable en continu (0/1)",
    "FLAG_PHONE": "Téléphone fixe renseigné (0/1)",
    "FLAG_EMAIL": "Adresse e-mail renseignée (0/1)",
    "OCCUPATION_TYPE": "Profession",
    "CNT_FAM_MEMBERS": "Nombre de membres dans le foyer",
    "REGION_RATING_CLIENT": "Note de la région (client)",
    "REGION_RATING_CLIENT_W_CITY": "Note de la région (client + ville)",
    "WEEKDAY_APPR_PROCESS_START": "Jour de la demande",
    "HOUR_APPR_PROCESS_START": "Heure de la demande",
    "REG_REGION_NOT_LIVE_REGION": "Région d'enregistrement ≠ région de résidence (0/1)",
    "REG_REGION_NOT_WORK_REGION": "Région d'enregistrement ≠ région de travail (0/1)",
    "LIVE_REGION_NOT_WORK_REGION": "Région de résidence ≠ région de travail (0/1)",
    "REG_CITY_NOT_LIVE_CITY": "Ville d'enregistrement ≠ ville de résidence (0/1)",
    "REG_CITY_NOT_WORK_CITY": "Ville d'enregistrement ≠ ville de travail (0/1)",
    "LIVE_CITY_NOT_WORK_CITY": "Ville de résidence ≠ ville de travail (0/1)",
    "ORGANIZATION_TYPE": "Type d'employeur",
    "EXT_SOURCE_1": "Score externe 1",
    "EXT_SOURCE_2": "Score externe 2",
    "EXT_SOURCE_3": "Score externe 3",

    "APARTMENTS_AVG": "Appartements (moyenne normalisée)",
    "BASEMENTAREA_AVG": "Sous-sol (moyenne normalisée)",
    "YEARS_BEGINEXPLUATATION_AVG": "Ancienneté bâtiment (moyenne normalisée)",
    "YEARS_BUILD_AVG": "Année de construction (moyenne normalisée)",
    "COMMONAREA_AVG": "Parties communes (moyenne normalisée)",
    "ELEVATORS_AVG": "Ascenseurs (moyenne normalisée)",
    "ENTRANCES_AVG": "Entrées immeuble (moyenne normalisée)",
    "FLOORSMAX_AVG": "Étages max (moyenne normalisée)",
    "FLOORSMIN_AVG": "Étages min (moyenne normalisée)",
    "LANDAREA_AVG": "Surface du terrain (moyenne normalisée)",
    "LIVINGAPARTMENTS_AVG": "Appartements habitables (moyenne normalisée)",
    "LIVINGAREA_AVG": "Surface habitable (moyenne normalisée)",
    "NONLIVINGAPARTMENTS_AVG": "Appartements non habitables (moyenne normalisée)",
    "NONLIVINGAREA_AVG": "Surface non habitable (moyenne normalisée)",

    "APARTMENTS_MODE": "Appartements (valeur la plus fréquente)",
    "BASEMENTAREA_MODE": "Sous-sol (valeur la plus fréquente)",
    "YEARS_BEGINEXPLUATATION_MODE": "Ancienneté bâtiment (valeur la plus fréquente)",
    "YEARS_BUILD_MODE": "Année de construction (valeur la plus fréquente)",
    "COMMONAREA_MODE": "Parties communes (valeur la plus fréquente)",
    "ELEVATORS_MODE": "Ascenseurs (valeur la plus fréquente)",
    "ENTRANCES_MODE": "Entrées immeuble (valeur la plus fréquente)",
    "FLOORSMAX_MODE": "Étages max (valeur la plus fréquente)",
    "FLOORSMIN_MODE": "Étages min (valeur la plus fréquente)",
    "LANDAREA_MODE": "Surface du terrain (valeur la plus fréquente)",
    "LIVINGAPARTMENTS_MODE": "Appartements habitables (valeur la plus fréquente)",
    "LIVINGAREA_MODE": "Surface habitable (valeur la plus fréquente)",
    "NONLIVINGAPARTMENTS_MODE": "Appartements non habitables (valeur la plus fréquente)",
    "NONLIVINGAREA_MODE": "Surface non habitable (valeur la plus fréquente)",

    "APARTMENTS_MEDI": "Appartements (médiane)",
    "BASEMENTAREA_MEDI": "Sous-sol (médiane)",
    "YEARS_BEGINEXPLUATATION_MEDI": "Ancienneté bâtiment (médiane)",
    "YEARS_BUILD_MEDI": "Année de construction (médiane)",
    "COMMONAREA_MEDI": "Parties communes (médiane)",
    "ELEVATORS_MEDI": "Ascenseurs (médiane)",
    "ENTRANCES_MEDI": "Entrées immeuble (médiane)",
    "FLOORSMAX_MEDI": "Étages max (médiane)",
    "FLOORSMIN_MEDI": "Étages min (médiane)",
    "LANDAREA_MEDI": "Surface du terrain (médiane)",
    "LIVINGAPARTMENTS_MEDI": "Appartements habitables (médiane)",
    "LIVINGAREA_MEDI": "Surface habitable (médiane)",
    "NONLIVINGAPARTMENTS_MEDI": "Appartements non habitables (médiane)",
    "NONLIVINGAREA_MEDI": "Surface non habitable (médiane)",

    "FONDKAPREMONT_MODE": "Type de fonds de rénovation",
    "HOUSETYPE_MODE": "Type de bâtiment",
    "TOTALAREA_MODE": "Surface totale du logement",
    "WALLSMATERIAL_MODE": "Matériau principal des murs",
    "EMERGENCYSTATE_MODE": "État d'urgence du bâtiment",

    "OBS_30_CNT_SOCIAL_CIRCLE": "Contacts avec retard < 30j (observés)",
    "DEF_30_CNT_SOCIAL_CIRCLE": "Contacts en défaut < 30j",
    "OBS_60_CNT_SOCIAL_CIRCLE": "Contacts avec retard < 60j (observés)",
    "DEF_60_CNT_SOCIAL_CIRCLE": "Contacts en défaut < 60j",
    "DAYS_LAST_PHONE_CHANGE": "Ancienneté du dernier changement de téléphone (jours, négatif)",

    "FLAG_DOCUMENT_2": "Document 2 fourni (0/1)",
    "FLAG_DOCUMENT_3": "Document 3 fourni (0/1)",
    "FLAG_DOCUMENT_4": "Document 4 fourni (0/1)",
    "FLAG_DOCUMENT_5": "Document 5 fourni (0/1)",
    "FLAG_DOCUMENT_6": "Document 6 fourni (0/1)",
    "FLAG_DOCUMENT_7": "Document 7 fourni (0/1)",
    "FLAG_DOCUMENT_8": "Document 8 fourni (0/1)",
    "FLAG_DOCUMENT_9": "Document 9 fourni (0/1)",
    "FLAG_DOCUMENT_10": "Document 10 fourni (0/1)",
    "FLAG_DOCUMENT_11": "Document 11 fourni (0/1)",
    "FLAG_DOCUMENT_12": "Document 12 fourni (0/1)",
    "FLAG_DOCUMENT_13": "Document 13 fourni (0/1)",
    "FLAG_DOCUMENT_14": "Document 14 fourni (0/1)",
    "FLAG_DOCUMENT_15": "Document 15 fourni (0/1)",
    "FLAG_DOCUMENT_16": "Document 16 fourni (0/1)",
    "FLAG_DOCUMENT_17": "Document 17 fourni (0/1)",
    "FLAG_DOCUMENT_18": "Document 18 fourni (0/1)",
    "FLAG_DOCUMENT_19": "Document 19 fourni (0/1)",
    "FLAG_DOCUMENT_20": "Document 20 fourni (0/1)",
    "FLAG_DOCUMENT_21": "Document 21 fourni (0/1)",

    "AMT_REQ_CREDIT_BUREAU_HOUR": "Demandes bureau de crédit (1 heure)",
    "AMT_REQ_CREDIT_BUREAU_DAY": "Demandes bureau de crédit (1 jour)",
    "AMT_REQ_CREDIT_BUREAU_WEEK": "Demandes bureau de crédit (1 semaine)",
    "AMT_REQ_CREDIT_BUREAU_MON": "Demandes bureau de crédit (1 mois)",
    "AMT_REQ_CREDIT_BUREAU_QRT": "Demandes bureau de crédit (1 trimestre)",
    "AMT_REQ_CREDIT_BUREAU_YEAR": "Demandes bureau de crédit (1 an)",

    # --- Features dérivées du projet 7 (base) ---
    "AGE_YEARS": "Âge du client (années)",
    "EMP_YEARS": "Ancienneté dans l'emploi (années)",
    "CREDIT_INCOME_RATIO": "Ratio crédit / revenu",
    "ANNUITY_INCOME_RATIO": "Ratio annuité / revenu",
    "ANNUITY_CREDIT_RATIO": "Ratio annuité / crédit",
    "GOODS_CREDIT_RATIO": "Part du bien financée à crédit",
    "EXT_SOURCE_1_x_EXT_SOURCE_2": "Interaction scores externes 1 × 2",
    "EXT_SOURCE_2_x_EXT_SOURCE_3": "Interaction scores externes 2 × 3",
    "EXT_SOURCE_1_x_EXT_SOURCE_3": "Interaction scores externes 1 × 3",
    "EXT_SOURCE_1_plus_EXT_SOURCE_2": "Somme scores externes 1 + 2",
    "EXT_SOURCE_2_plus_EXT_SOURCE_3": "Somme scores externes 2 + 3",
    "EXT_SOURCE_1_plus_EXT_SOURCE_3": "Somme scores externes 1 + 3",

    # =========================
    #   FEATURES SHAP (num__/cat__)
    # =========================

    "num__ANNUITY_CREDIT_RATIO": "Ratio annuité / crédit",
    "num___GOODS_CREDIT_RATIO": "Part du bien financée à crédit",
    "num__EXT_SOURCE_1": "Score externe 1",
    "num__EXT_SOURCE_3": "Score externe 3",
    "num__DAYS_BIRTH": "Âge (jours, négatif)",
    "num__EXT_SOURCE_2": "Score externe 2",
    "num__EXT_SOURCE_2_plus_EXT_SOURCE_3": "Somme des scores externes 2 + 3",
    "num__DAYS_ID_PUBLISH": "Ancienneté de mise à jour des papiers (jours, négatif)",
    "num__DAYS_LAST_PHONE_CHANGE": "Ancienneté du dernier changement de téléphone (jours, négatif)",
    "num__AMT_ANNUITY": "Montant de l’annuité",
    "num__DAYS_REGISTRATION": "Ancienneté de l’inscription (jours, négatif)",
    "num__ANNUITY_INCOME_RATIO": "Ratio annuité / revenu",
    "num__CREDIT_INCOME_RATIO": "Ratio crédit / revenu",
    "num__REGION_POPULATION_RELATIVE": "Population relative de la région",
    "num__SK_ID_CURR": "Identifiant client",
    "num__DAYS_EMPLOYED": "Ancienneté dans l’emploi (jours, négatif)",
    "num__EXT_SOURCE_2_x_EXT_SOURCE_3": "Interaction entre les scores externes 2 × 3",
    "num__AGE_YEARS": "Âge du client (années)",
    "num__AMT_GOODS_PRICE": "Prix du bien financé",
    "num__AMT_CREDIT": "Montant du crédit demandé",
    "num__AMT_INCOME_TOTAL": "Revenu annuel",
    "num__EXT_SOURCE_1_plus_EXT_SOURCE_2": "Somme des scores externes 1 + 2",
    "num__EMP_YEARS": "Ancienneté dans l’emploi (années)",
    "num__EXT_SOURCE_1_x_EXT_SOURCE_3": "Interaction entre les scores externes 1 × 3",
    "num__EXT_SOURCE_1_x_EXT_SOURCE_2": "Interaction entre les scores externes 1 × 2",
    "num__OWN_CAR_AGE": "Âge du véhicule (années)",
    "num__HOUR_APPR_PROCESS_START": "Heure de la demande de crédit",
    "num__EXT_SOURCE_1_plus_EXT_SOURCE_3": "Somme des scores externes 1 + 3",
    "num__AMT_REQ_CREDIT_BUREAU_YEAR": "Demandes au bureau de crédit (1 an)",
    "num__TOTALAREA_MODE": "Surface totale du logement (valeur la plus fréquente)",
    "num__BASEMENTAREA_MODE": "Surface de sous-sol (valeur la plus fréquente)",
    "num__LANDAREA_AVG": "Surface du terrain (moyenne normalisée)",
    "num__YEARS_BEGINEXPLUATATION_AVG": "Ancienneté du bâtiment (moyenne normalisée)",
    "num__REGION_RATING_CLIENT_W_CITY": "Note de la région (client + ville)",
    "num__APARTMENTS_MODE": "Surface des appartements (valeur la plus fréquente)",
    "num__LANDAREA_MODE": "Surface du terrain (valeur la plus fréquente)",
    "num__LIVINGAREA_AVG": "Surface habitable (moyenne normalisée)",
    "num__COMMONAREA_AVG": "Surface des parties communes (moyenne normalisée)",
    "num__AMT_REQ_CREDIT_BUREAU_QRT": "Demandes au bureau de crédit (1 trimestre)",
    "num__NONLIVINGAREA_MODE": "Surface non habitable (valeur la plus fréquente)",
    "num__BASEMENTAREA_AVG": "Surface de sous-sol (moyenne normalisée)",
    "num__OBS_30_CNT_SOCIAL_CIRCLE": "Contacts avec retard < 30 jours (observés)",
    "cat__NAME_CONTRACT_TYPE_Cash_loans": "Type de contrat : Prêt à la consommation",
    "num__AMT_REQ_CREDIT_BUREAU_MON": "Demandes au bureau de crédit (1 mois)",
    "cat__CODE_GENDER_F": "Sexe : Femme",
    "num__COMMONAREA_MODE": "Surface des parties communes (valeur la plus fréquente)",
    "cat__FLAG_OWN_CAR_N": "Possède une voiture : Non",
    "num__NONLIVINGAREA_AVG": "Surface non habitable (moyenne normalisée)",
    "cat__NAME_FAMILY_STATUS_Married": "Situation familiale : Marié(e)",
    "num__YEARS_BUILD_AVG": "Année de construction (moyenne normalisée)",
    "num__YEARS_BEGINEXPLUATATION_MODE": "Ancienneté du bâtiment (valeur la plus fréquente)",
    "num__APARTMENTS_AVG": "Surface des appartements (moyenne normalisée)",
    "num__FLAG_WORK_PHONE": "Téléphone de travail renseigné (0/1)",
    "num__YEARS_BEGINEXPLUATATION_MEDI": "Ancienneté du bâtiment (médiane)",
    "num__LIVINGAPARTMENTS_AVG": "Nombre d’appartements habitables (moyenne normalisée)",
    "num__FLAG_DOCUMENT_3": "Document 3 fourni (0/1)",
    "num__OBS_60_CNT_SOCIAL_CIRCLE": "Contacts avec retard < 60 jours (observés)",
    "num__LIVINGAREA_MODE": "Surface habitable (valeur la plus fréquente)",
    "num__YEARS_BUILD_MODE": "Année de construction (valeur la plus fréquente)",
    "num__DEF_30_CNT_SOCIAL_CIRCLE": "Contacts en défaut < 30 jours",
    "cat__NAME_EDUCATION_TYPE_Higher_education": "Niveau d’étude : Études supérieures",
    "num__ENTRANCES_AVG": "Nombre d’entrées de l’immeuble (moyenne normalisée)",
    "cat__CODE_GENDER_M": "Sexe : Homme",
    "num__DEF_60_CNT_SOCIAL_CIRCLE": "Contacts en défaut < 60 jours",
    "num__BASEMENTAREA_MEDI": "Surface de sous-sol (médiane)",
    "num__NONLIVINGAREA_MEDI": "Surface non habitable (médiane)",
    "cat__NAME_EDUCATION_TYPE_Secondary_secondary_special": "Niveau d’étude : Secondaire / professionnel",
    "num__LANDAREA_MEDI": "Surface du terrain (médiane)",
    "num__LIVINGAREA_MEDI": "Surface habitable (médiane)",
    "num__COMMONAREA_MEDI": "Surface des parties communes (médiane)",
    "num__LIVINGAPARTMENTS_MODE": "Nombre d’appartements habitables (valeur la plus fréquente)",
    "num__CNT_FAM_MEMBERS": "Nombre de membres dans le foyer",
    "num__FLOORSMAX_AVG": "Nombre d’étages max (moyenne normalisée)",
    "num__NONLIVINGAPARTMENTS_AVG": "Nombre d’appartements non habitables (moyenne normalisée)",
    "cat__ORGANIZATION_TYPE_Industry_type_9": "Type d’employeur : Industry type 9",
    "cat__ORGANIZATION_TYPE_Self_employed": "Type d’employeur : Indépendant",
    "num__NONLIVINGAPARTMENTS_MODE": "Nombre d’appartements non habitables (valeur la plus fréquente)",
    "num__FLOORSMIN_AVG": "Nombre d’étages min (moyenne normalisée)",
    "num__LIVINGAPARTMENTS_MEDI": "Nombre d’appartements habitables (médiane)",
    "num__REG_CITY_NOT_LIVE_CITY": "Ville d’enregistrement ≠ ville de résidence (0/1)",
    "num__CNT_CHILDREN": "Nombre d’enfants",
    "cat__WEEKDAY_APPR_PROCESS_START_SATURDAY": "Jour de la demande : Samedi",
    "cat__ORGANIZATION_TYPE_Military": "Type d’employeur : Armée / militaire",
    "cat__ORGANIZATION_TYPE_Transport_type_3": "Type d’employeur : Transport type 3",
    "num__FLAG_DOCUMENT_16": "Document 16 fourni (0/1)",
    "cat__WEEKDAY_APPR_PROCESS_START_WEDNESDAY": "Jour de la demande : Mercredi",
    "cat__NAME_HOUSING_TYPE_House_apartment": "Type de logement : Maison / appartement",
    "cat__ORGANIZATION_TYPE_School": "Type d’employeur : École",
    "cat__NAME_INCOME_TYPE_Working": "Type de revenu : Salarié",
    "num__FLAG_PHONE": "Téléphone fixe renseigné (0/1)",
    "cat__ORGANIZATION_TYPE_Realtor": "Type d’employeur : Agence immobilière",
    "num__LIVE_CITY_NOT_WORK_CITY": "Ville de résidence ≠ ville de travail (0/1)",
    "num__APARTMENTS_MEDI": "Surface des appartements (médiane)",
    "cat__OCCUPATION_TYPE_Core_staff": "Profession : Personnel clé",
    "cat__OCCUPATION_TYPE_Accountants": "Profession : Comptable",
    "num__REGION_RATING_CLIENT": "Note de la région (client)",
    "num__ENTRANCES_MEDI": "Nombre d’entrées de l’immeuble (médiane)",
    "cat__ORGANIZATION_TYPE_Construction": "Type d’employeur : Construction / BTP",
    "num__AMT_REQ_CREDIT_BUREAU_WEEK": "Demandes au bureau de crédit (1 semaine)",
    "cat__OCCUPATION_TYPE_High_skill_tech_staff": "Profession : Personnel technique qualifié",
    "cat__NAME_EDUCATION_TYPE_Academic_degree": "Niveau d’étude : Diplôme universitaire",
    "cat__NAME_TYPE_SUITE_Unaccompanied": "Accompagnement : Seul(e)",
    "num__ENTRANCES_MODE": "Nombre d’entrées de l’immeuble (valeur la plus fréquente)",
    "num__FLAG_DOCUMENT_18": "Document 18 fourni (0/1)",
    "cat__ORGANIZATION_TYPE_Security_Ministries": "Type d’employeur : Ministères de la sécurité",
    "num__FLOORSMAX_MEDI": "Nombre d’étages max (médiane)",
    "cat__WALLSMATERIAL_MODE_Stone_brick": "Matériau des murs : Pierre / brique",
    "num__YEARS_BUILD_MEDI": "Année de construction (médiane)",
    "cat__OCCUPATION_TYPE_Drivers": "Profession : Chauffeur",
    "cat__NAME_INCOME_TYPE_State_servant": "Type de revenu : Fonctionnaire",
    "num__ELEVATORS_AVG": "Nombre d’ascenseurs (moyenne normalisée)",
    "cat__NAME_INCOME_TYPE_Unemployed": "Type de revenu : Sans emploi",
    "cat__OCCUPATION_TYPE_Managers": "Profession : Cadre / manager",
    "num__FLOORSMIN_MEDI": "Nombre d’étages min (médiane)",
    "cat__WEEKDAY_APPR_PROCESS_START_MONDAY": "Jour de la demande : Lundi",
    "num__FLAG_DOCUMENT_13": "Document 13 fourni (0/1)",
    "cat__ORGANIZATION_TYPE_Government": "Type d’employeur : Administration publique",
    "num__FLAG_EMAIL": "Adresse e-mail renseignée (0/1)",
    "cat__NAME_FAMILY_STATUS_Single_not_married": "Situation familiale : Célibataire",
    "num__FLAG_DOCUMENT_14": "Document 14 fourni (0/1)",
    "cat__NAME_HOUSING_TYPE_Office_apartment": "Type de logement : Appartement de fonction",
    "cat__WEEKDAY_APPR_PROCESS_START_SUNDAY": "Jour de la demande : Dimanche",
    "num__FLOORSMAX_MODE": "Nombre d’étages max (valeur la plus fréquente)",
    "cat__FONDKAPREMONT_MODE_reg_oper_spec_account": "Fonds de rénovation : Compte dédié (régie)",
    "cat__ORGANIZATION_TYPE_Bank": "Type d’employeur : Banque",
    "cat__WEEKDAY_APPR_PROCESS_START_TUESDAY": "Jour de la demande : Mardi",
    "num__FLAG_DOCUMENT_8": "Document 8 fourni (0/1)",
    "num__FLOORSMIN_MODE": "Nombre d’étages min (valeur la plus fréquente)",
    "cat__ORGANIZATION_TYPE_Trade_type_2": "Type d’employeur : Commerce type 2",
    "cat__NAME_FAMILY_STATUS_Civil_marriage": "Situation familiale : Union civile",
    "num__ELEVATORS_MODE": "Nombre d’ascenseurs (valeur la plus fréquente)",
    "cat__ORGANIZATION_TYPE_Kindergarten": "Type d’employeur : Crèche / maternelle",
    "cat__OCCUPATION_TYPE_Medicine_staff": "Profession : Personnel médical",
    "cat__ORGANIZATION_TYPE_Business_Entity_Type_3": "Type d’employeur : Société type 3",
    "cat__ORGANIZATION_TYPE_Police": "Type d’employeur : Police",
    "cat__NAME_HOUSING_TYPE_Municipal_apartment": "Type de logement : Appartement municipal",
    "cat__NAME_INCOME_TYPE_Commercial_associate": "Type de revenu : Associé commercial / indépendant",
    "cat__ORGANIZATION_TYPE_Industry_type_12": "Type d’employeur : Industry type 12",
    "num__FLAG_DOCUMENT_11": "Document 11 fourni (0/1)",
    "cat__NAME_TYPE_SUITE_Spouse_partner": "Accompagnement : Conjoint / partenaire",
    "num__REG_CITY_NOT_WORK_CITY": "Ville d’enregistrement ≠ ville de travail (0/1)",
    "cat__NAME_EDUCATION_TYPE_Lower_secondary": "Niveau d’étude : Collège",
    "cat__ORGANIZATION_TYPE_Medicine": "Type d’employeur : Secteur médical",
    "num__FLAG_DOCUMENT_15": "Document 15 fourni (0/1)",
    "cat__NAME_FAMILY_STATUS_Widow": "Situation familiale : Veuf / veuve",
    "cat__ORGANIZATION_TYPE_Transport_type_2": "Type d’employeur : Transport type 2",
    "cat__ORGANIZATION_TYPE_Business_Entity_Type_1": "Type d’employeur : Société type 1",
    "cat__OCCUPATION_TYPE_Laborers": "Profession : Manoeuvre / ouvrier",
    "cat__ORGANIZATION_TYPE_Hotel": "Type d’employeur : Hôtellerie",
    "cat__NAME_TYPE_SUITE_Family": "Accompagnement : Famille",
    "num__AMT_REQ_CREDIT_BUREAU_DAY": "Demandes au bureau de crédit (1 jour)",
    "cat__OCCUPATION_TYPE_Sales_staff": "Profession : Vendeur / commercial",
    "cat__OCCUPATION_TYPE_Security_staff": "Profession : Sécurité",
    "cat__OCCUPATION_TYPE_Private_service_staff": "Profession : Services à la personne",
    "cat__WALLSMATERIAL_MODE_Panel": "Matériau des murs : Panneaux",
    "cat__FONDKAPREMONT_MODE_reg_oper_account": "Fonds de rénovation : Compte standard (régie)",
    "num__ELEVATORS_MEDI": "Nombre d’ascenseurs (médiane)",
    "cat__NAME_EDUCATION_TYPE_Incomplete_higher": "Niveau d’étude : Supérieur inachevé",
    "num__REG_REGION_NOT_LIVE_REGION": "Région d’enregistrement ≠ région de résidence (0/1)",
    "cat__FLAG_OWN_REALTY_N": "Possède un bien immobilier : Non",
    "cat__ORGANIZATION_TYPE_Business_Entity_Type_2": "Type d’employeur : Société type 2",
    "cat__ORGANIZATION_TYPE_Legal_Services": "Type d’employeur : Services juridiques",
    "cat__WEEKDAY_APPR_PROCESS_START_FRIDAY": "Jour de la demande : Vendredi",
    "cat__ORGANIZATION_TYPE_University": "Type d’employeur : Université",
    "num__FLAG_EMP_PHONE": "Téléphone professionnel renseigné (0/1)",
    "num__LIVE_REGION_NOT_WORK_REGION": "Région de résidence ≠ région de travail (0/1)",
    "cat__OCCUPATION_TYPE_Low_skill_Laborers": "Profession : Ouvrier peu qualifié",
    "cat__ORGANIZATION_TYPE_Other": "Type d’employeur : Autre",
    "cat__ORGANIZATION_TYPE_Restaurant": "Type d’employeur : Restauration",
    "num__FLAG_DOCUMENT_6": "Document 6 fourni (0/1)",
    "cat__OCCUPATION_TYPE_Waiters_barmen_staff": "Profession : Serveur / barman",
    "cat__WALLSMATERIAL_MODE_Others": "Matériau des murs : Autres",
    "num__REG_REGION_NOT_WORK_REGION": "Région d’enregistrement ≠ région de travail (0/1)",
    "cat__NAME_HOUSING_TYPE_Rented_apartment": "Type de logement : Appartement loué",
    "num__NONLIVINGAPARTMENTS_MEDI": "Nombre d’appartements non habitables (médiane)",
    "cat__WALLSMATERIAL_MODE_Block": "Matériau des murs : Bloc",
    "cat__ORGANIZATION_TYPE_Trade_type_6": "Type d’employeur : Commerce type 6",
    "cat__ORGANIZATION_TYPE_Trade_type_4": "Type d’employeur : Commerce type 4",
    "cat__OCCUPATION_TYPE_Cleaning_staff": "Profession : Agent de nettoyage",
    "cat__WEEKDAY_APPR_PROCESS_START_THURSDAY": "Jour de la demande : Jeudi",
    "cat__ORGANIZATION_TYPE_Housing": "Type d’employeur : Organisme de logement",
    "cat__ORGANIZATION_TYPE_Trade_type_3": "Type d’employeur : Commerce type 3",
    "cat__ORGANIZATION_TYPE_Services": "Type d’employeur : Services",
    "cat__ORGANIZATION_TYPE_Industry_type_1": "Type d’employeur : Industry type 1",
    "cat__FONDKAPREMONT_MODE_org_spec_account": "Fonds de rénovation : Compte dédié (organisme)",
    "cat__NAME_TYPE_SUITE_Other_A": "Accompagnement : Autre (A)",
    "cat__ORGANIZATION_TYPE_Transport_type_1": "Type d’employeur : Transport type 1",
    "cat__ORGANIZATION_TYPE_Telecom": "Type d’employeur : Télécommunications",
    "cat__ORGANIZATION_TYPE_Industry_type_5": "Type d’employeur : Industry type 5",
    "cat__NAME_HOUSING_TYPE_With_parents": "Type de logement : Chez les parents",
    "cat__ORGANIZATION_TYPE_Advertising": "Type d’employeur : Publicité / communication",
    "cat__ORGANIZATION_TYPE_Trade_type_1": "Type d’employeur : Commerce type 1",
    "cat__NAME_FAMILY_STATUS_Separated": "Situation familiale : Séparé(e)",
    "cat__ORGANIZATION_TYPE_Industry_type_2": "Type d’employeur : Industry type 2",
    "cat__HOUSETYPE_MODE_terraced_house": "Type de bâtiment : Maison mitoyenne",
    "cat__WALLSMATERIAL_MODE_Monolithic": "Matériau des murs : Monolithique",
    "num__FLAG_DOCUMENT_5": "Document 5 fourni (0/1)",
    "cat__EMERGENCYSTATE_MODE_No": "État d’urgence : Non",
    "cat__NAME_HOUSING_TYPE_Co_op_apartment": "Type de logement : Appartement en coopérative",
    "cat__ORGANIZATION_TYPE_Postal": "Type d’employeur : Services postaux",
    "num__FLAG_DOCUMENT_17": "Document 17 fourni (0/1)",
    "cat__ORGANIZATION_TYPE_Agriculture": "Type d’employeur : Agriculture",
    "cat__ORGANIZATION_TYPE_Trade_type_7": "Type d’employeur : Commerce type 7",
    "cat__OCCUPATION_TYPE_Cooking_staff": "Profession : Personnel de cuisine",
    "cat__OCCUPATION_TYPE_Secretaries": "Profession : Secrétaire",
    "cat__FLAG_OWN_CAR_Y": "Possède une voiture : Oui",
    "cat__FONDKAPREMONT_MODE_not_specified": "Fonds de rénovation : Non spécifié",
    "cat__ORGANIZATION_TYPE_Mobile": "Type d’employeur : Téléphonie mobile",
    "cat__OCCUPATION_TYPE_Realty_agents": "Profession : Agent immobilier",
    "cat__ORGANIZATION_TYPE_Cleaning": "Type d’employeur : Nettoyage",
    "cat__ORGANIZATION_TYPE_Transport_type_4": "Type d’employeur : Transport type 4",
    "cat__ORGANIZATION_TYPE_Insurance": "Type d’employeur : Assurances",
    "cat__OCCUPATION_TYPE_IT_staff": "Profession : Informatique",
    "cat__WALLSMATERIAL_MODE_Wooden": "Matériau des murs : Bois",
    "cat__ORGANIZATION_TYPE_XNA": "Type d’employeur : Inconnu",
    "cat__ORGANIZATION_TYPE_Trade_type_5": "Type d’employeur : Commerce type 5",
    "cat__ORGANIZATION_TYPE_Security": "Type d’employeur : Sécurité",
    "cat__HOUSETYPE_MODE_specific_housing": "Type de bâtiment : Logement spécifique",
    "cat__WALLSMATERIAL_MODE_Mixed": "Matériau des murs : Mixte",
    "cat__HOUSETYPE_MODE_block_of_flats": "Type de bâtiment : Immeuble collectif",
    "cat__NAME_TYPE_SUITE_Group_of_people": "Accompagnement : Groupe de personnes",
    "cat__ORGANIZATION_TYPE_Religion": "Type d’employeur : Organisation religieuse",
    "cat__ORGANIZATION_TYPE_Industry_type_8": "Type d’employeur : Industry type 8",
    "cat__FLAG_OWN_REALTY_Y": "Possède un bien immobilier : Oui",
    "cat__CODE_GENDER_XNA": "Sexe : Inconnu",
    "cat__NAME_CONTRACT_TYPE_Revolving_loans": "Type de contrat : Crédit renouvelable",
    "num__AMT_REQ_CREDIT_BUREAU_HOUR": "Demandes au bureau de crédit (1 heure)",
    "num__FLAG_DOCUMENT_21": "Document 21 fourni (0/1)",
    "num__FLAG_DOCUMENT_20": "Document 20 fourni (0/1)",
    "num__FLAG_DOCUMENT_19": "Document 19 fourni (0/1)",
    "num__FLAG_DOCUMENT_12": "Document 12 fourni (0/1)",
    "num__FLAG_DOCUMENT_10": "Document 10 fourni (0/1)",
    "num__FLAG_DOCUMENT_9": "Document 9 fourni (0/1)",
    "num__FLAG_DOCUMENT_7": "Document 7 fourni (0/1)",
    "num__FLAG_DOCUMENT_4": "Document 4 fourni (0/1)",
    "num__FLAG_DOCUMENT_2": "Document 2 fourni (0/1)",
    "num__FLAG_CONT_MOBILE": "Mobile joignable en continu (0/1)",
    "num__FLAG_MOBIL": "Téléphone mobile renseigné (0/1)",
    "cat__NAME_TYPE_SUITE_Children": "Accompagnement : Enfants",
    "cat__NAME_TYPE_SUITE_Other_B": "Accompagnement : Autre (B)",
    "cat__NAME_INCOME_TYPE_Businessman": "Type de revenu : Chef d’entreprise",
    "cat__ORGANIZATION_TYPE_Industry_type_10": "Type d’employeur : Industry type 10",
    "cat__ORGANIZATION_TYPE_Industry_type_7": "Type d’employeur : Industry type 7",
    "cat__ORGANIZATION_TYPE_Industry_type_6": "Type d’employeur : Industry type 6",
    "cat__ORGANIZATION_TYPE_Industry_type_4": "Type d’employeur : Industry type 4",
    "cat__ORGANIZATION_TYPE_Industry_type_3": "Type d’employeur : Industry type 3",
    "cat__ORGANIZATION_TYPE_Industry_type_13": "Type d’employeur : Industry type 13",
    "cat__ORGANIZATION_TYPE_Industry_type_11": "Type d’employeur : Industry type 11",
    "cat__ORGANIZATION_TYPE_Emergency": "Type d’employeur : Urgences",
    "cat__NAME_INCOME_TYPE_Maternity_leave": "Type de revenu : Congé maternité",
    "cat__ORGANIZATION_TYPE_Electricity": "Type d’employeur : Énergie / électricité",
    "cat__ORGANIZATION_TYPE_Culture": "Type d’employeur : Secteur culturel",
    "cat__OCCUPATION_TYPE_HR_staff": "Profession : Ressources humaines",
    "cat__NAME_FAMILY_STATUS_Unknown": "Situation familiale : Inconnue",
    "cat__NAME_INCOME_TYPE_Student": "Type de revenu : Étudiant",
    "cat__NAME_INCOME_TYPE_Pensioner": "Type de revenu : Retraité",
    "cat__EMERGENCYSTATE_MODE_Yes": "État d’urgence : Oui"
}

def feature_label(name: str) -> str:
    """Retourne le libellé FR, ou le nom brut si non trouvé."""
    return FEATURE_LABELS.get(name, name)
